#include <concord/error.h>
static inline char * ccordcode_to_str(CCORDcode code) {
	switch (code) {
		case CCORD_MALFORMED_PAYLOAD: return "CCORD_MALFORMED_PAYLOAD";
		case CCORD_FULL_WORKER: return "CCORD_FULL_WORKER";
		case CCORD_RESOURCE_UNAVAILABLE: return "CCORD_RESOURCE_UNAVAILABLE";
		case CCORD_RESOURCE_OWNERSHIP: return "CCORD_RESOURCE_OWNERSHIP";
		case CCORD_GLOBAL_INIT: return "CCORD_GLOBAL_INIT";
		case CCORD_CURLM_INTERNAL: return "CCORD_CURLM_INTERNAL";
		case CCORD_CURLE_INTERNAL: return "CCORD_CURLE_INTERNAL";
		case CCORD_BAD_JSON: return "CCORD_BAD_JSON";
		case CCORD_BAD_PARAMETER: return "CCORD_BAD_PARAMETER";
		case CCORD_UNUSUAL_HTTP_CODE: return "CCORD_UNUSUAL_HTTP_CODE";
		case CCORD_CURL_NO_RESPONSE: return "CCORD_CURL_NO_RESPONSE";
		case CCORD_HTTP_CODE: return "CCORD_HTTP_CODE";
		case CCORD_OK: return "CCORD_OK";
		case CCORD_PENDING: return "CCORD_PENDING";
		case CCORD_DISCORD_JSON_CODE: return "CCORD_DISCORD_JSON_CODE";
		case CCORD_DISCORD_BAD_AUTH: return "CCORD_DISCORD_BAD_AUTH";
		case CCORD_DISCORD_RATELIMIT: return "CCORD_DISCORD_RATELIMIT";
		case CCORD_DISCORD_CONNECTION: return "CCORD_DISCORD_CONNECTION";
		default: return "Unknown";
	}
}
